### PR TITLE
Feat: generate plugin options docs

### PR DESCRIPTION
**Pull request by TylerBarnes**
This PR adds a script which generates plugin options docs.

### CODE REVIEW

**Comment by TylerBarnes** [comment]
This is ready for review!

btw @mxstbr you might find this interesting. I'm using your plugin options schema API to generate our plugin options documentation https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/8f51f075b44ee22564cf94c599454dd25ea75eda/docs/plugin-options.md

It used to be manually maintained 😱 
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/plugin-options.md

**Review by jasonbahl — APPROVED** [review]
@TylerBarnes this looks 🔥 

Only thing I think we should follow up with (whenever) is to automate this. Any PR where the plugin options change should maybe re-generate the plugin options automatically? 

The CI part can be addressed anytime though.

**Comment by TylerBarnes** [comment]
Thanks @jasonbahl and good call on automation. I left it out for now because I'm not 100% sure what that'll look like in the Gatsby monorepo.

**Comment by jasonbahl** [comment]
Ah ya. . .monorepo 😬

**Pull request merged**
