### PR TITLE
Update check-plugin-requirements.js

### PR DESCRIPTION
**Pull request by AdrianLuk**
Fixing a typo

### CODE REVIEW

**Comment by TylerBarnes** [comment]
Awesome, thank you! :D

**Comment by acao** [comment]
this broke the master build :(

**Comment by TylerBarnes** [comment]
I think that was unrelated actually :) See https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/pull/314#issuecomment-736802331 and https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/pull/334/files

It's nothing you did @AdrianLuk 😄

**Comment by acao** [comment]
yes my bad, meant to be clear on that, nothing you changed caused this @AdrianLuk, was just tagging Tyler here because of a related issue

**Comment by AdrianLuk** [comment]
Yeah I'm sure nothing I did should have changed it....it's just a log anyway :) first open source contribution so excited even if it's just a small typo fix. Thanks y'all

**Comment by TylerBarnes** [comment]
That's awesome! Congratulations 😄 🎉

**Pull request merged**
